### ISSUE TITLE
Add support for indexes

### ISSUE THREAD

**Issue by garrows** [chilts/awssum-amazon-dynamodb#1]
Need to update to API version 2012-08-10 from 2011-12-05.

Thanks.

**Comment by chilts** [comment]
Specifically, this is for the local secondary indexes.
- http://aws.typepad.com/aws/2013/04/local-secondary-indexes-for-amazon-dynamodb.html

Thanks Glen.

**Comment by chilts** [comment]
Deprecated: please use aws-sdk.
